POST http://localhost:3000/tasks/save_tasks
Content-Type: application/json

{
  "data": ["list1"]
}

###

GET http://localhost:3000/user/get_users

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
  "username": "minh",
  "password": "pass"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "minh",
  "password": "pass"
}